### ISSUE TITLE
Needless fork of github.com/pkg/errors ?

### ISSUE THREAD

**Issue by onlyjob** [openSUSE/umoci#244]
Vendored [github.com/pkg/errors](https://github.com/pkg/errors) appears to be a fork since building against pristine library produces the following error:

~~~~
# github.com/openSUSE/umoci/cmd/umoci
src/github.com/openSUSE/umoci/cmd/umoci/main.go:97:4: undefined: "github.com/pkg/errors".Debug
~~~~

Indeed vendored library appears to be modified as I could not find traces of `Debug` in the original library repository.

Needless forking is harmful. Please consider using unmodified library.

If you have to (use the) fork of the original library for whatever reason then at least please don't hijack its import path.

Thank you.

**Comment by cyphar** [comment]
Thanks, I am working on fixing this in a branch. The short explanation of why it was done is that I had submitted a PR to upstream and assumed it would be merged -- they rejected it outright and I didn't have time to do the work to remove it and implement it properly.

If you want to see the patch, take a look inside `hack/`. You should probably know that I have [another patch for an upstream project](https://github.com/openSUSE/umoci/blob/master/hack/runtime-tools-0001-generate-remove-validate-dependency.patch) which has an upstream PR but it takes forever to get anything merged -- and this patch actually is required in order for builds to work properly (without depending on SELinux bindings)...

> Needless forking is harmful [...] at least please don't hijack its import path.

I'm applying the same logic as with distribution packages (in openSUSE we apply patches on top of packages if it's necessary). I recognise that in Debian you folks have to un-vendor projects and that this is going to be a problem for you -- so I'm happy to help as much as I can. But I'm pretty sure making a fork of the projects just for one patch would cause a similar amount of headaches (because you'd have to make new packages).

Nonetheless, I will work on fixing this up.

**Comment by onlyjob** [comment]
Thank you.

In Debian we can apply patches when necessary but introducing this patch to _pkg/errors_ package just for the sake of _umoci_ does not feel like a right solution...
Shipping modified private library is also not ideal... I hope that eventually this problem can be fixed...

**Comment by cyphar** [comment]
`pkg/errors` is much easier to fix than `github.com/opencontainers/runtime-tools` -- but luckily `umoci` will build with the regular upstream `runtime-tools` package IIRC (the patch is mainly to avoid including some of the upstream vendored projects -- but this shouldn't change the build outcome if you have the original sources).
