### ISSUE TITLE
Incompatibilities with colons (and possibly other characters) in extended scope reference names

### ISSUE THREAD

**Issue by rlifshay** [openSUSE/umoci#265]
#234 expanded the scope of possible reference names, however there are several commands/parameters that still do not fully support them. I am trying to use references of the form `test.com/proj:1.2.3` and the colon is causing problems. They work fine as the second parameter to the tag command, but not when copying a tag with a colon or creating a new tag with the new command.

```
$ umoci -v
umoci version 0.4.2
$
```

Works:
```
$ umoci tag --image blah:latest asd/qwe:ew
$
```
Doesn't work:
```
$ umoci tag --image blah:asd/qwe:ew testing
...
   ⨯ invalid --image: path contains ':' character: 'blah:asd/qwe'
$ umoci new --image blah:asd/qwe:ew
...
   ⨯ invalid --image: path contains ':' character: 'blah:asd/qwe'
$

**Comment by cyphar** [comment]
Okay, what's happening is that we are parsing `--image` paths with `:` incorrectly -- in particular we are assuming that only the last `:` is the tag delimiter and also disallowing paths with `:`. This is really strange and I don't remember why I wrote it this way :cold_sweat:. I believe the concern was that using `:` as a tag delimiter was a bad idea, and I wanted to avoid people using complicated paths so I could change it in the future.

At the moment, I've agreed with the KIWI folks that the UX is effectively frozen until umoci 2.x (if that ever happens) so we can change this so that the `:` is correctly handled. The only downside is that people might end up doing something like `--image image:test:hello` would result in `image` being accessed under the tag` test:hello` while users might expect `image:test` being accessed with the tag `hello`. :confused:

**Comment by rlifshay** [comment]
Oh okay cool. I was looking later and saw some instances in the code that assume the colon is the last delimeter as you say. It doesn't appear though that people could currently access `image:test` with the tag `hello` because after extracting `image:test` as the image name, the code explicitly checks whether there is a colon in the filename. If it finds one, it puts out the error messages from my earlier examples.

**Comment by cyphar** [comment]
I think #266 should fix it, but I only played with it very superficially.
