### ISSUE TITLE
Rootless config generates invalid mount for /etc/resolv.conf

### ISSUE THREAD

**Issue by rneilson** [openSUSE/umoci#294]
Using `umoci unpack --rootless` (or `umoci raw config --rootless`), an extra mount is generated for `/etc/resolv.conf`, with `"type": "none"` [1](https://github.com/openSUSE/umoci/blob/master/oci/layer/unpack.go#L356). This causes `runc` to parse the mount with the default (directory) behavior [2](https://github.com/opencontainers/runc/blob/master/libcontainer/specconv/spec_linux.go#L279), trying to create the destination as a directory instead of a file [3](https://github.com/opencontainers/runc/blob/v1.0.0-rc6/libcontainer/rootfs_linux.go#L387).

TBH, not sure if this is a runtime spec problem, a `runc` mount parsing problem, or a `umoci` config generation problem, but I'm guessing it's most easily fixed here.

To reproduce:
```
> skopeo copy docker://busybox:latest oci:busybox:latest
> umoci raw unpack --rootless --image busybox rootfs
> umoci raw config --image=busybox --rootless --rootfs=rootfs config.json
> runc run busybox
container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/resolv.conf\\\" to rootfs \\\"/data/contained/temp/rootfs\\\" at \\\"/data/contained/temp/rootfs/etc/resolv.conf\\\" caused \\\"not a directory\\\"\""
```

`umoci --version`
```
umoci version 0.4.4
```

`runc --version `
```
runc version 1.0.0-rc6
spec: 1.0.1-dev
```

**Comment by cyphar** [comment]
The `resolv.conf` mount is usually necessary, but I think the issue might be that the rootfs doesn't already have a `resolv.conf` and so runc gets a bit confused? I will take a look at this...

**Comment by rneilson** [comment]
I tried adding an empty `resolv.conf` to the rootfs as an empty file before running the container, and I get another, related error instead:
```
container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/resolv.conf\\\" to rootfs \\\"/data/contained/unpacked/busybox/rootfs\\\" at \\\"/data/contained/unpacked/busybox/rootfs/etc/resolv.conf\\\" caused \\\"mkdir /data/contained/unpacked/busybox/rootfs/etc/resolv.conf: not a directory\\\"\""
```

However, if I change the mount to `"type": "bind"`, it works fine (with or without `resolv.conf` in the rootfs).

**Comment by cyphar** [comment]
Right, yeah this sounds familiar.

opencontainers/runc#1753 *should* have fixed this (previously we'd treated `type: bind` as special which was incorrect for several reasons) but that fix only makes it so that an **empty** `type` is changed to `bind` (which is required because internally the `rootfs_linux.go` code heavily relies on `type: bind`).

The solution from the `umoci` side is to not add a `type` to the bind-mount (even though it should work) -- but I should also fix this in `runc`.

**Comment by cyphar** [comment]
What's really odd is that this definitely worked for a *very* long time -- there must've been a `runc` change which regressed this.

**Comment by cyphar** [comment]
opencontainers/runc#2035 fixes the `runc` issue, and I'll submit a PR which will fix it for older `runc` releases. The `runc` patch will probably be included in `1.0.0-rc8`.

**Comment by cyphar** [comment]
And openSUSE/umoci#295 fixes this.

**Comment by cyphar** [comment]
What's really odd is that this definitely worked for a very long time -- there must've been a `runc` change which regressed this.

I've submitted opencontainers/runc#2035 which will fix the upstream issue, as well as openSUSE/umoci#295 which will fix the local issue. Let me know if it fixes the issue for you.

(I do plan to use `runc` as part of the integration tests but I've historically been a bit cautious about it, because Travis has had issues with `runc`'s CI in the past.)

**Comment by rneilson** [comment]
Thanks. Wrangled a Go build*, and seems to work. Expectedly, but still.

* The makefile is, for some reason, trying to install into /usr/bin/ instead of ~/bin/
